<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audit.proto

namespace GPBMetadata;

class Audit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab8020a0b61756469742e70726f746f22670a0d61756469745f6d657373" .
            "61676512260a06636f6d6d697418012001280b32142e636f6d6d69745f6e" .
            "6f74696669636174696f6e480012270a0d6c65616465725f737461747573" .
            "18022001280b320e2e6c65616465725f737461747573480042050a036d73" .
            "6722660a0d6c65616465725f737461747573120c0a047465726d18012001" .
            "2804120e0a066c656164657218022001280912190a1163757272656e745f" .
            "6c6f675f696e646578180320012804121c0a1463757272656e745f636f6d" .
            "6d69745f696e64657818042001280422500a13636f6d6d69745f6e6f7469" .
            "6669636174696f6e12130a0b73656e6465725f7575696418012001280912" .
            "110a096c6f675f696e64657818022001280412110a096f7065726174696f" .
            "6e180320012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

