<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluzelle.proto

namespace GPBMetadata;

class Bluzelle
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Database::initOnce();
        \GPBMetadata\Audit::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d010a0e626c757a656c6c652e70726f746f1a0b61756469742e70726f" .
            "746f22660a07627a6e5f6d7367121b0a026462180a2001280b320d2e6461" .
            "7461626173655f6d73674800120e0a046a736f6e180b2001280948001227" .
            "0a0d61756469745f6d657373616765180c2001280b320e2e61756469745f" .
            "6d657373616765480042050a036d7367620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

