<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audit.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>audit_message</code>
 */
class audit_message extends \Google\Protobuf\Internal\Message
{
    protected $msg;

    public function __construct() {
        \GPBMetadata\Audit::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.commit_notification commit = 1;</code>
     * @return \commit_notification
     */
    public function getCommit()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.commit_notification commit = 1;</code>
     * @param \commit_notification $var
     * @return $this
     */
    public function setCommit($var)
    {
        GPBUtil::checkMessage($var, \commit_notification::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.leader_status leader_status = 2;</code>
     * @return \leader_status
     */
    public function getLeaderStatus()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.leader_status leader_status = 2;</code>
     * @param \leader_status $var
     * @return $this
     */
    public function setLeaderStatus($var)
    {
        GPBUtil::checkMessage($var, \leader_status::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMsg()
    {
        return $this->whichOneof("msg");
    }

}

