<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluzelle.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bzn_msg</code>
 */
class bzn_msg extends \Google\Protobuf\Internal\Message
{
    protected $msg;

    public function __construct() {
        \GPBMetadata\Bluzelle::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.database_msg db = 10;</code>
     * @return \database_msg
     */
    public function getDb()
    {
        return $this->readOneof(10);
    }

    /**
     * Generated from protobuf field <code>.database_msg db = 10;</code>
     * @param \database_msg $var
     * @return $this
     */
    public function setDb($var)
    {
        GPBUtil::checkMessage($var, \database_msg::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string json = 11;</code>
     * @return string
     */
    public function getJson()
    {
        return $this->readOneof(11);
    }

    /**
     * Generated from protobuf field <code>string json = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.audit_message audit_message = 12;</code>
     * @return \audit_message
     */
    public function getAuditMessage()
    {
        return $this->readOneof(12);
    }

    /**
     * Generated from protobuf field <code>.audit_message audit_message = 12;</code>
     * @param \audit_message $var
     * @return $this
     */
    public function setAuditMessage($var)
    {
        GPBUtil::checkMessage($var, \audit_message::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMsg()
    {
        return $this->whichOneof("msg");
    }

}

