<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audit.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>commit_notification</code>
 */
class commit_notification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sender_uuid = 1;</code>
     */
    private $sender_uuid = '';
    /**
     * Generated from protobuf field <code>uint64 log_index = 2;</code>
     */
    private $log_index = 0;
    /**
     * Generated from protobuf field <code>string operation = 3;</code>
     */
    private $operation = '';

    public function __construct() {
        \GPBMetadata\Audit::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string sender_uuid = 1;</code>
     * @return string
     */
    public function getSenderUuid()
    {
        return $this->sender_uuid;
    }

    /**
     * Generated from protobuf field <code>string sender_uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 log_index = 2;</code>
     * @return int|string
     */
    public function getLogIndex()
    {
        return $this->log_index;
    }

    /**
     * Generated from protobuf field <code>uint64 log_index = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLogIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->log_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operation = 3;</code>
     * @return string
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * Generated from protobuf field <code>string operation = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation = $var;

        return $this;
    }

}

