<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>database_header</code>
 */
class database_header extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string db_uuid = 1;</code>
     */
    private $db_uuid = '';
    /**
     * Generated from protobuf field <code>uint64 transaction_id = 2;</code>
     */
    private $transaction_id = 0;

    public function __construct() {
        \GPBMetadata\Database::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string db_uuid = 1;</code>
     * @return string
     */
    public function getDbUuid()
    {
        return $this->db_uuid;
    }

    /**
     * Generated from protobuf field <code>string db_uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 transaction_id = 2;</code>
     * @return int|string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>uint64 transaction_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->transaction_id = $var;

        return $this;
    }

}

