<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Database.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>database_response</code>
 */
class database_response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.database_header header = 1;</code>
     */
    private $header = null;
    protected $success;

    public function __construct() {
        \GPBMetadata\Database::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.database_header header = 1;</code>
     * @return \database_header
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.database_header header = 1;</code>
     * @param \database_header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \database_header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.database_redirect_response redirect = 2;</code>
     * @return \database_redirect_response
     */
    public function getRedirect()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.database_redirect_response redirect = 2;</code>
     * @param \database_redirect_response $var
     * @return $this
     */
    public function setRedirect($var)
    {
        GPBUtil::checkMessage($var, \database_redirect_response::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.database_response.response resp = 3;</code>
     * @return \database_response_response
     */
    public function getResp()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.database_response.response resp = 3;</code>
     * @param \database_response_response $var
     * @return $this
     */
    public function setResp($var)
    {
        GPBUtil::checkMessage($var, \database_response_response::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getSuccess()
    {
        return $this->whichOneof("success");
    }

}

