<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Database.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>database_response.response</code>
 */
class database_response_response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes value = 4;</code>
     */
    private $value = '';
    /**
     * Generated from protobuf field <code>bool has = 5;</code>
     */
    private $has = false;
    /**
     * Generated from protobuf field <code>int32 size = 6;</code>
     */
    private $size = 0;
    /**
     * Generated from protobuf field <code>string error = 7;</code>
     */
    private $error = '';
    /**
     * Generated from protobuf field <code>repeated string keys = 8;</code>
     */
    private $keys;

    public function __construct() {
        \GPBMetadata\Database::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes value = 4;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool has = 5;</code>
     * @return bool
     */
    public function getHas()
    {
        return $this->has;
    }

    /**
     * Generated from protobuf field <code>bool has = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setHas($var)
    {
        GPBUtil::checkBool($var);
        $this->has = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 size = 6;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>int32 size = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error = 7;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->keys = $arr;

        return $this;
    }

}

