<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Database.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>database_empty</code>
 */
class database_empty extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Database::initOnce();
        parent::__construct();
    }

}

